apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: microservice-iot-sample-global
    component: microservice-iot-sample-global
  name: microservice-iot-sample-global
  namespace: microservice-iot-sample
data:
  base-config.yaml: |
    security:
      jersey:
        enabled: false
        prematching-authentication: true
        prematching-authorization: true
      providers:
      - http-basic-auth:
          users:
          - login: user
            password: user
            roles:
            - BCA_INTERNAL_ROLE
    tenant:
      iadpromo99999954507_lite:
        database:
          connection:
            inactiveTimeout: 600
            poolInit: 1
            poolMax: 5
            poolMin: 0
          url: jdbc:oracle:thin:@iotiadinfdpatp_tp?TNS_ADMIN=/data/configs/.secrets/wallets
        namespace: iadpromo99999954507-lite
        services:
          iot: http://internal-lb.iadpromo99999954507-lite.svc.cluster.local:8001
  log4j2.yaml: |-
    "Configuration":
      "Appenders":
        "Console":
          "PatternLayout":
            "pattern": "%d{yyyy-MMM-dd HH:mm:ss a} [%t] %-5level %logger{36} - %msg%n"
          "name": "Console"
          "target": "SYSTEM_OUT"
      "Loggers":
        "Root":
          "AppenderRef":
            - "ref": "Console"
          "level": "debug"
        "logger":
          - "level": "info"
            "name": "org.glassfish.jersey"
          - "level": "info"
            "name": "io.helidon"
          - "level": "info"
            "name": "io.netty"

